server:
  port: 18081
  context-path: /message
spring:
  application:
    name: shop-message
  activemq:
    broker-url: tcp://39.106.35.109:61616
    in-memory: true
    pool:
      enabled: false
  mail:
    host: smtp.163.com
    username: zhouhaojun8080@163.com
    password: 15030619382zhou
    enable: true
    smtp:
      auth: true
    starttls:
      enable: true
      required: true
eureka:
  client:
    serviceUrl:
      defaultZone: http://39.106.35.109:8761/eureka/

msg:
  subject: 蚂蚁课堂|每特教育提示您，会员注册成功邮件。
  text:  恭喜您的账户{},注册成功!蚂蚁课堂|每特教育 上海每特教育科技有限公司 www.itmayiedu.com

queue: message
