server:
  port: 18083

spring:
  application:
    name: shop-order
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/order
    username: root
    password: 150306

  redis:
    host: 39.106.35.109
    port: 6379
    password: 123456

eureka:
  client:
    service-url:
      defalultZone: http://39.106.35.109:8761/eureka/
